// C:\Projects\RetiaPlayground\Retia\Retia\Helpers\CollectionExtensions.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Helpers\MatrixPointers.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Helpers\StreamHelpers.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\ConsoleProgressWriter.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\ICloneable.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\IFileWritable.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\ILogReporter.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\IProgressWriter.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\IStreamWritable.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\LogEventArgs.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\ProgressEventArgs.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Integration\ProgressTracker.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\MathProviderImplD.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\Fir.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\MathProvider.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\MathProviderBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\MatrixExtensions.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\MatrixFactory.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Mathematics\MathProviderImpl.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\BiGRU.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Initializers\ConstantMatrixInitializer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Initializers\IMatrixInitializer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Initializers\ProportionalRandomMatrixInitializer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Initializers\RandomMatrixInitializer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\LayeredNet.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\DropoutLayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\GRULayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\LinearLayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\ModulusLayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\NeuroLayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\SoftMaxLayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\Layers\TanhLayer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\NeuralExtensions.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\NeuralNet.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Neural\NeuroWeight.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Optimizers\AdagradOptimizer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Optimizers\OptimizerBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Optimizers\RMSPropOptimizer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Properties\AssemblyInfo.cs
// C:\Projects\RetiaPlayground\Retia\Retia\RandomGenerator\BaseRandom.cs
// C:\Projects\RetiaPlayground\Retia\Retia\RandomGenerator\IRandom.cs
// C:\Projects\RetiaPlayground\Retia\Retia\RandomGenerator\SafeRandom.cs
// C:\Projects\RetiaPlayground\Retia\Retia\RandomGenerator\UniformRandom.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Batching\BatchDimension.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Batching\LinearBatcher.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Batching\LinearSample.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Batching\SequenceBatcher.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\DataProviderBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\DataSetChangedArgs.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\IDataProvider.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\IDataSet.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\LinearDataSet.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\Sample.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\SequentialDataSet.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\SetDataProvider.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Data\TrainingSequence.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Testers\ClassificationTester.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Testers\ClassResult.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Testers\ConfusionMatrix.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Testers\ITester.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Testers\TesterBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Testers\TestResultBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\ITrainingReporter.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\OptimizationReportEventArgs.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\OptimizingTrainer.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\OptimizingTrainerOptions.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\PeriodicalAction.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\TrainerBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\TrainerOptionsBase.cs
// C:\Projects\RetiaPlayground\Retia\Retia\Training\Trainers\TrainReportEventArgsBase.cs
